parameters:
#    sifast_pfe.example.class: Sifast\PfeBundle\Example

services:
#    sifast_pfe.example:
#        class: %sifast_pfe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
